### ISSUE TITLE
Question: is this plugin thread safe?

### ISSUE THREAD

**Issue by gjoranv** [phax/ph-javacc-maven-plugin#12]
Can the plugin be safely used in multi threaded builds with e.g. `--threads 2C`? We are considering switching to this plugin from the old javacc-maven-plugin which is not thread safe.

**Comment by phax** [comment]
I must admit I have never tested it multithreaded.
I was reading through https://cwiki.apache.org/confluence/display/MAVEN/Parallel+builds+in+Maven+3 and check and I'm not using one of
>plexus-utils 2.0.5 maven-archiver 2.4.1 plexus-archiver 1.0 plexus-io 1.0

So in general (considering the main programming style), it should work :)
If not, please file an issue with stacktrace and I will fix it.

**Comment by gjoranv** [comment]
Thanks! We switched to this plugin, and on our setup it failed in 3 out of 5 multi threaded builds, more or less like the old javacc plugin. I'll create a new issue with the two different stacktraces that were found. Great if you could look into it.
