### ISSUE TITLE
JavaCC Mojo doesn't call addCompileSourceRoot()

### ISSUE THREAD

**Issue by vmassol** [phax/ph-javacc-maven-plugin#17]
Hi,

Thanks for your plugin. Right now the plugin is not a "good Maven citizen" since it doesn't add the generated sources to the maven compile source roots, which prevents other plugins from finding the generated sources.

It would be great if you could add. For example this is done in the antlr plugin at https://github.com/antlr/antlr4/blob/master/antlr4-maven-plugin/src/main/java/org/antlr/mojo/antlr4/Antlr4Mojo.java#L204

Thanks!

**Comment by phax** [comment]
Well, actually it does call it (theoretically):
https://github.com/phax/ph-javacc-maven-plugin/blob/master/src/main/java/org/codehaus/mojo/javacc/AbstractJavaCCMojo.java#L733

**Comment by phax** [comment]
As it does some debug logging I tried the existing version 4.1.4 on ph-css with the Maven parameters "-e -X" and found this in the log:
```
[DEBUG] Adding compile source root: C:\dev\git\ph-css\ph-css\target\generated-sources\javacc
[DEBUG] Adding compile source root: C:\dev\git\ph-css\ph-css\target\generated-sources\jjtree
```
So I guess that means, it calls it....

**Comment by vmassol** [comment]
Indeed I can see it called at https://github.com/phax/ph-javacc-maven-plugin/blob/master/src/main/java/org/codehaus/mojo/javacc/AbstractJavaCCMojo.java#L719

That's weird. I'm trying to debug an issue with another maven plugin (spoon). I'll check more.

Thanks for your fast answer @phax !

Closing for now.
