### ISSUE TITLE
Update to JavaCC 7.0.2

### ISSUE THREAD

**Issue by phax** [phax/ph-javacc-maven-plugin#2]
From https://github.com/javacc/javacc/releases/tag/release_7_0_2 and check if it is quicker than 6.1.3

**Comment by andrewparmet** [comment]
I think this might also remove the obnoxious safety-throws for forgotten return statements, i.e.
```java
{if ("" != null) return result;}
    throw new Error("Missing return statement in function");
  }
```

**Comment by matozoid** [comment]
We at https://github.com/javaparser/javaparser would like this too :-) Thanks for taking over development of this!

**Comment by phax** [comment]
I need to wait for https://github.com/javacc/javacc/pull/29 to be merged and the next JavaCC release (probably 7.1.0).

**Comment by matozoid** [comment]
@phax can you do the talking in https://github.com/javacc/javacc/issues/37 ?

**Comment by phax** [comment]
JavaCC 7.0.3 is out - http://repo2.maven.org/maven2/net/java/dev/javacc/javacc/7.0.3/ -  I will test it and release it if adequate!

**Comment by matozoid** [comment]
Woohoo :-D

**Comment by phax** [comment]
6 month later v3.0.0 is here....
