### ISSUE TITLE
Question: can we make this a Maven 3 plugin?

### ISSUE THREAD

**Issue by phax** [phax/ph-javacc-maven-plugin#4]
Currently this plugin requires Maven 2.0.4 as the minimum version.
Are there any objections against making Maven 3 the minimum required version?

**Comment by phax** [comment]
@andrewparmet @matozoid @wenerme Any opinions on this one???

**Comment by matozoid** [comment]
Fine with us!

**Comment by phax** [comment]
Maven 3.0 is is :)
