### ISSUE TITLE
Cannot configure input and output folders

### ISSUE THREAD

**Issue by lordkada** [phax/ph-javacc-maven-plugin#8]
Hi,
I'm trying to configure this plugin for my project, but I'm having hard times, probably I'm doing something wrong.
Basically it looks that it doesn't really take care of the given source directory (in my case `src/main/jjtree2`) or the ouputDirectory path (`/generated-sources/jjtreeA` ... I have also tried other stuff, like `/src/my path`).
It just uses the default input (`src/main/jjtree`) and output paths (`/generated-sources/javacc` and `/generated-sources/jjtree`).
Where am I wrong?

```
      <plugin>
        <groupId>com.helger.maven</groupId>
        <artifactId>ph-javacc-maven-plugin</artifactId>
        <version>4.0.1</version>
        <executions>
          <execution>
            <id>jjt1</id>
            <phase>generate-sources</phase>
            <goals>
              <goal>jjtree-javacc</goal>
            </goals>
            <configuration>
              <jdkVersion>1.8</jdkVersion>
              <sourceDirectory>src/main/jjtree2</sourceDirectory>
              <excludes>
                <exclude>**/parser/**</exclude>
              </excludes>
              <outputDirectory>${project.build.directory}/generated-sources/jjtreeA</outputDirectory>
            </configuration>
          </execution>
        </executions>
      </plugin>
```

**Comment by lordkada** [comment]
I have found that moving the configuration out of the `<executions>` block makes it partially working. The input and output are respected, but not the `jjtree` classes (i.e. Node, SimpleNode,  ...).

**Comment by phax** [comment]
I assume this is kind of Maven specific - try adding `${basedir}/` in front of your source directory to make the path absolute? I see nothing wrong - from the top of my head....

**Comment by phax** [comment]
I checked it with the following setup and it works:
```xml
      <plugin>
        <groupId>com.helger.maven</groupId>
        <artifactId>ph-javacc-maven-plugin</artifactId>
        <version>4.0.1</version>
        <executions>
          <execution>
            <id>one</id>
            <goals>
              <goal>jjtree-javacc</goal>
            </goals>
            <configuration>
              <jdkVersion>1.8</jdkVersion>
              <javadocFriendlyComments>true</javadocFriendlyComments>
              <userCharStream>true</userCharStream>
              <outputDirectory>${project.build.directory}/bla</outputDirectory>
            </configuration>
          </execution>
          <execution>
            <id>two</id>
            <goals>
              <goal>jjtree-javacc</goal>
            </goals>
            <configuration>
              <jdkVersion>1.8</jdkVersion>
              <javadocFriendlyComments>true</javadocFriendlyComments>
              <userCharStream>true</userCharStream>
              <outputDirectory>${project.build.directory}/bla2</outputDirectory>
            </configuration>
          </execution>
        </executions>
      </plugin>
```

**Comment by lordkada** [comment]
Hey, thanks for your prompt reply...!
Unfortunately it still doesn't work.. Here you can see the output on the left (still in the default folders) and the excerpt of the pom on the right. Furthermore, as you can see, the `javadocFriendlyComments` is marked as wrongly placed there (in fact in my original pom I removed it, to avoid any interference)

![screen shot 2018-03-06 at 10 55 43](https://user-images.githubusercontent.com/1006711/37025835-093add9c-212d-11e8-8e37-853d0483f332.png)

**Comment by phax** [comment]
1. Yes, `javadocFriendlyComments` is unsupported - just ignore it :)
2. I also have the folder `target/generate-sources/javacc`  - it is an intermediate folder
3. I have the folders `target/bla` and `target/bla2` - please check outside your IDE as well - sometimes IDEs automatically add this to the "build path"

**Comment by phax** [comment]
Maybe you also need to set the property `interimDirectory` per execution as well!

**Comment by lordkada** [comment]
Thanks for your suggestions.. I need to check the `interimDirectory`, but in the meantime this is a record from my terminal:

[asciinema](https://asciinema.org/a/c27r2NrVhUqUroG2SjZN84L58)

**Comment by lordkada** [comment]
FYI: it looks to me that also the `interimDirectory` isn't taken care of.

**Comment by phax** [comment]
I'm a Windows user, with JDK 1.8.0_144 and the following config:
```xml
      <plugin>
        <groupId>com.helger.maven</groupId>
        <artifactId>ph-javacc-maven-plugin</artifactId>
        <version>4.0.1</version>
        <executions>
          <execution>
            <id>one</id>
            <goals>
              <goal>jjtree-javacc</goal>
            </goals>
            <configuration>
              <jdkVersion>1.8</jdkVersion>
              <userCharStream>true</userCharStream>
              <interimDirectory>${project.build.directory}/interim</interimDirectory>
              <outputDirectory>${project.build.directory}/bla</outputDirectory>
            </configuration>
          </execution>
          <execution>
            <id>two</id>
            <goals>
              <goal>jjtree-javacc</goal>
            </goals>
            <configuration>
              <jdkVersion>1.8</jdkVersion>
              <userCharStream>true</userCharStream>
              <interimDirectory>${project.build.directory}/interim2</interimDirectory>
              <outputDirectory>${project.build.directory}/bla2</outputDirectory>
            </configuration>
          </execution>
        </executions>
      </plugin>
```

Output (relevant parts):

```
.....\ph-css\target>dir
06.03.2018  11:32    <DIR>          .
06.03.2018  11:32    <DIR>          ..
06.03.2018  11:32    <DIR>          bla
06.03.2018  11:32    <DIR>          bla2
06.03.2018  11:32    <DIR>          buildinfo-maven-plugin
06.03.2018  11:32    <DIR>          classes
06.03.2018  11:32    <DIR>          interim
06.03.2018  11:32    <DIR>          interim2
               0 Datei(en),              0 Bytes
```

**Comment by phax** [comment]
I'm using `mvn clean process-resources` for processing

**Comment by lordkada** [comment]
Ok, I made it working by:
- using the `interimDirectory` as you pointed out
- executing `mvn clean process-resources` instead of `mvn ph-javacc:jjtree-javacc`

If I remove the `interimDirectory`, it stops working.
If I use `mvn ph-javacc:jjtree-javacc` the jjtree classes are generated in the default folder

**Comment by lordkada** [comment]
Basically this is my final (working) pom, and I run it by using `mvn clean process-resources`:

```
      <plugin>
        <groupId>com.helger.maven</groupId>
        <artifactId>ph-javacc-maven-plugin</artifactId>
        <version>${javacc-maven-plugin.version}</version>
        <executions>
          <execution>
            <id>jjt1</id>
            <phase>generate-sources</phase>
            <goals>
              <goal>jjtree-javacc</goal>
            </goals>
            <configuration>
              <jdkVersion>1.8</jdkVersion>
              <userCharStream>true</userCharStream>
              <sourceDirectory>src/main/jjtree</sourceDirectory>
              <interimDirectory>${project.basedir}/src/main/java</interimDirectory>
              <outputDirectory>${project.basedir}/src/main/java</outputDirectory>
            </configuration>
          </execution>
        </executions>
      </plugin>
```

**Comment by lordkada** [comment]
FYI I can also rid of `${project.basedir}` by using:
```
              ...
              <interimDirectory>src/main/java</interimDirectory>
              <outputDirectory>src/main/java</outputDirectory>
             ...
```
and it still works.

**Comment by phax** [comment]
Okay - so the basic issue was, that you invoked "just the plugin" in which case the "phase" selector potentially didn't drop in properly... weird - Maven internals. Anyway glad you solved it :)
